[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[inputs.mqtt_consumer]]
  servers = ["tcp://172.20.10.8:1883"]
  topics = ["home/sensor/data"]
  data_format = "json"
  json_time_key = "timestamp"
  json_time_format = "unix"
  name_override = "mqtt_consumer"
  qos = 0
  persistent_session = false
  client_id = "telegraf_weather_station"

[[processors.rename]]
  [[processors.rename.replace]]
    field = "temperature"
    dest = "temperature_dht"

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  token = "YOUR_INFLUXDB_TOKEN_HERE"
  organization = "YOUR_ORG_NAME"
  bucket = "YOUR_BUCKET_NAME"